In [1]:
#إنشاء نموذج ذكاء اصطناعي يمكنه التنبؤ بمدى قدرة الأشخاص على سداد القروض، أي ما إذا كان الشخص "جديرًا بالائتمان" أم لا.

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

data= pd.read_csv('/content/credit_risk_dataset.csv')
data.head()

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4

1-loan_intent(الغرض من القرض التعليم,السياره)
2-loan_grade(تصنيف جوده القرض حسب الجداره الائتمانيه)
3-loan_status(هل تم السداد أم حدث تعثر)
4-loan_int_rate(سعر الفائدة )
5-loan_percent_income( نسبة مبلغ القرض إلى دخل الشخص)
6-cb_person_default_on_file( هل لدى الشخص تعثر سابق في السجل الائتماني (نعم أو لا))
7-cb_preson_cred_hist_length(عدد السنوات التي يمتلك فيها الشخص سجلًا ائتمانيًا.)

In [2]:
data.shape

(32581, 12)

In [3]:
data.describe()

,person_age,person_income,person_emp_length,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_cred_hist_length
count,32581.000000,3.258100e+04,31686.000000,32581.000000,29465.000000,32581.000000,32581.000000,32581.000000
mean,27.734600,6.607485e+04,4.789686,9589.371106,11.011695,0.218164,0.170203,5.804211
std,6.348078,6.198312e+04,4.142630,6322.086646,3.240459,0.413006,0.106782,4.055001
min,20.000000,4.000000e+03,0.000000,500.000000,5.420000,0.000000,0.000000,2.000000
25%,23.000000,3.850000e+04,2.000000,5000.000000,7.900000,0.000000,0.090000,3.000000
50%,26.000000,5.500000e+04,4.000000,8000.000000,10.990000,0.000000,0.150000,4.000000
75%,30.000000,7.920000e+04,7.000000,12200.000000,13.470000,0.000000,0.230000,8.000000
max,144.000000,6.000000e+06,123.000000,35000.000000,23.220000,1.000000,0.830000,30.000000

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 12 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   person_age                  32581 non-null  int64
 1   person_income               32581 non-null  int64
 2   person_home_ownership       32581 non-null  object
 3   person_emp_length           31686 non-null  float64
 4   loan_intent                 32581 non-null  object
 5   loan_grade                  32581 non-null  object
 6   loan_amnt                   32581 non-null  int64
 7   loan_int_rate               29465 non-null  float64
 8   loan_status                 32581 non-null  int64
 9   loan_percent_income         32581 non-null  float64
 10  cb_person_default_on_file   32581 non-null  object
 11  cb_person_cred_hist_length  32581 non-null  int64
dtypes: float64(3), int64(5), object(4)
memory usage: 3.0+ MB

In [5]:
data.isnull().sum()

person_age                       0
person_income                    0
person_home_ownership            0
person_emp_length              895
loan_intent                      0
loan_grade                       0
loan_amnt                        0
loan_int_rate                 3116
loan_status                      0
loan_percent_income              0
cb_person_default_on_file        0
cb_person_cred_hist_length       0
dtype: int64

In [6]:
for i in data.select_dtypes(include='object').columns:
    print(data[i].value_counts())
    print('Unique Values :')
    print(data[i].unique())

person_home_ownership
RENT        16446
MORTGAGE    13444
OWN          2584
OTHER         107
Name: count, dtype: int64
Unique Values :
['RENT' 'OWN' 'MORTGAGE' 'OTHER']
loan_intent
EDUCATION            6453
MEDICAL              6071
VENTURE              5719
PERSONAL             5521
DEBTCONSOLIDATION    5212
HOMEIMPROVEMENT      3605
Name: count, dtype: int64
Unique Values :
['PERSONAL' 'EDUCATION' 'MEDICAL' 'VENTURE' 'HOMEIMPROVEMENT'
 'DEBTCONSOLIDATION']
loan_grade
A    10777
B    10451
C     6458
D     3626
E      964
F      241
G       64
Name: count, dtype: int64
Unique Values :
['D' 'B' 'C' 'A' 'E' 'F' 'G']
cb_person_default_on_file
N    26836
Y     5745
Name: count, dtype: int64
Unique Values :
['Y' 'N']

In [7]:
#if data is object
#data['column_name'].fillna('Unknown', inplace=True)
#if numeric
data['person_emp_length'] =data['person_emp_length'].fillna(data['person_emp_length'].mean())
data['loan_int_rate'] =data['loan_int_rate'].fillna(data['loan_int_rate'].mean())

In [8]:
data.isnull().sum()

person_age                    0
person_income                 0
person_home_ownership         0
person_emp_length             0
loan_intent                   0
loan_grade                    0
loan_amnt                     0
loan_int_rate                 0
loan_status                   0
loan_percent_income           0
cb_person_default_on_file     0
cb_person_cred_hist_length    0
dtype: int64

In [9]:
import numpy as np

# Detect outliers for each numerical column using the IQR method
numeric_cols = data.select_dtypes(include=[np.number]).columns

for col in numeric_cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    outliers = data[(data[col] < lower_bound) | (data[col] > upper_bound)]

    print(f"{col}: {outliers.shape[0]} outliers")

person_age: 1494 outliers
person_income: 1484 outliers
person_emp_length: 853 outliers
loan_amnt: 1689 outliers
loan_int_rate: 70 outliers
loan_status: 7108 outliers
loan_percent_income: 651 outliers
cb_person_cred_hist_length: 1142 outliers

In [10]:
#loan_grade with label encoder the rest with one hot encodeing
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
data['loan_grade']= le.fit_transform(data['loan_grade'])

In [11]:
from sklearn.preprocessing import OneHotEncoder

# Initialize the encoder
encoder = OneHotEncoder(sparse_output=False, drop='first')  # remove drop='first' if you want all categories

# Select the categorical columns
categorical_cols = ['person_home_ownership', 'loan_intent', 'cb_person_default_on_file']

# Fit and transform the data
encoded_data = encoder.fit_transform(data[categorical_cols])

# Create a DataFrame with the encoded features
encoded_df = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out(categorical_cols))

# Concatenate with the original DataFrame (excluding the original categorical columns)
df_encoded = pd.concat([data.drop(columns=categorical_cols), encoded_df], axis=1)

In [12]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32581 entries, 0 to 32580
Data columns (total 18 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   person_age                   32581 non-null  int64
 1   person_income                32581 non-null  int64
 2   person_emp_length            32581 non-null  float64
 3   loan_grade                   32581 non-null  int64
 4   loan_amnt                    32581 non-null  int64
 5   loan_int_rate                32581 non-null  float64
 6   loan_status                  32581 non-null  int64
 7   loan_percent_income          32581 non-null  float64
 8   cb_person_cred_hist_length   32581 non-null  int64
 9   person_home_ownership_OTHER  32581 non-null  float64
 10  person_home_ownership_OWN    32581 non-null  float64
 11  person_home_ownership_RENT   32581 non-null  float64
 12  loan_intent_EDUCATION        32581 non-null  float64
 13  loan_intent_HOMEIMPROVEMENT  32581 non-null  float64
 14  loan_intent_MEDICAL          32581 non-null  float64
 15  loan_intent_PERSONAL         32581 non-null  float64
 16  loan_intent_VENTURE          32581 non-null  float64
 17  cb_person_default_on_file_Y  32581 non-null  float64
dtypes: float64(12), int64(6)
memory usage: 4.5 MB

In [13]:
from sklearn.model_selection import train_test_split
x=df_encoded.drop('loan_status', axis=1)
y=df_encoded['loan_status']
x_train,x_test,y_train,y_test= train_test_split(x,y, test_size=0.2, random_state=42)

In [14]:
print("Train columns:", x_train.columns)
print("Test columns:", x_test.columns)
#making sure train and test columns are the same after splitting and nothing is missing

Train columns: Index(['person_age', 'person_income', 'person_emp_length', 'loan_grade',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'cb_person_default_on_file_Y'],
      dtype='object')
Test columns: Index(['person_age', 'person_income', 'person_emp_length', 'loan_grade',
       'loan_amnt', 'loan_int_rate', 'loan_percent_income',
       'cb_person_cred_hist_length', 'person_home_ownership_OTHER',
       'person_home_ownership_OWN', 'person_home_ownership_RENT',
       'loan_intent_EDUCATION', 'loan_intent_HOMEIMPROVEMENT',
       'loan_intent_MEDICAL', 'loan_intent_PERSONAL', 'loan_intent_VENTURE',
       'cb_person_default_on_file_Y'],
      dtype='object')

In [15]:
print(set(x_train.columns) - set(x_test.columns))  # what's in train but not in test
print(set(x_test.columns) - set(x_train.columns))  # what's in test but not in train

set()
set()

In [16]:
#random forest
from sklearn.ensemble import RandomForestClassifier
#after using grid search these were the best hyper parameters
forest = RandomForestClassifier(n_estimators=100 ,criterion= 'gini', max_depth= None,random_state= 42)

forest.fit(x_train, y_train)
# Predict on test set
y_pred= forest.predict(x_test)

In [17]:
from sklearn.metrics import accuracy_score
#accuracy
accuracy= accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy*100,"%")

Model Accuracy: 93.20239373945067 %

In [18]:
#Feature scaling isn’t necessary for RandomForest
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[5023   49]
 [ 394 1051]]
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5072
           1       0.96      0.73      0.83      1445

    accuracy                           0.93      6517
   macro avg       0.94      0.86      0.89      6517
weighted avg       0.93      0.93      0.93      6517

In [ ]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'n_estimators': [10, 50, 100],# Number of trees in the forest
    'max_depth': [None, 10, 20], # Maximum depth of each tree(None means unlimited depth).
    'criterion': ['gini', 'entropy'] # Split criteria for decision trees
}

grid_search = GridSearchCV(RandomForestClassifier(), param_grid, cv=5, scoring='accuracy')
#cv=5 -> 5-fold cross-validation is used (splitting data into 5 parts, training on 4, and testing on 1).
#scoring='accuracy -> The performance metric used to evaluate each set of hyperparameters.
grid_search.fit(x_train, y_train)
#This trains multiple RandomForestClassifier models using different combinations of hyperparameters from param_grid.

#Each model is evaluated using cross-validation, and the best combination is selected.
print(grid_search.best_params_)

{'criterion': 'gini', 'max_depth': None, 'n_estimators': 100}

In [19]:
from sklearn.tree import DecisionTreeClassifier
clf=DecisionTreeClassifier(random_state=42)
clf.fit(x_train,y_train)

y_perd=clf.predict(x_test)

In [20]:
accuracy=accuracy_score(y_test,y_pred)
print(f"the model's accuracy: {accuracy*100} % ")

the model's accuracy: 93.20239373945067 %

In [34]:
from xgboost import XGBClassifier

model = XGBClassifier(learning_rate= 0.1, max_depth=5, n_estimators= 200, subsample= 1.0)
model.fit(x_train, y_train)

# Predictions
y_pred = model.predict(x_test)

In [35]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
#accuracy
accuracy= accuracy_score(y_test, y_pred)
print("Model Accuracy:", accuracy*100,"%")

Confusion Matrix:
[[5036   36]
 [ 393 1052]]

Classification Report:
              precision    recall  f1-score   support

           0       0.93      0.99      0.96      5072
           1       0.97      0.73      0.83      1445

    accuracy                           0.93      6517
   macro avg       0.95      0.86      0.89      6517
weighted avg       0.94      0.93      0.93      6517

Model Accuracy: 93.41721651066442 %

In [33]:
from sklearn.model_selection import GridSearchCV

# Define the model
model = XGBClassifier()

# Define the hyperparameter grid
param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [3, 5, 7],
    'learning_rate': [0.01, 0.1, 0.2],
    'subsample': [0.8, 1.0]
}

# Set up GridSearchCV
grid_search = GridSearchCV(
    estimator=model,
    param_grid=param_grid,
    scoring='accuracy',
    cv=5,               # 5-fold cross-validation
    verbose=1,
    n_jobs=-1           # Use all available CPU cores
)

# Run the grid search
grid_search.fit(x_train, y_train)

# Best parameters and score
print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
Best Parameters: {'learning_rate': 0.1, 'max_depth': 5, 'n_estimators': 200, 'subsample': 1.0}
Best Accuracy: 0.9367325826174866

In [29]:
from sklearn.svm import SVC


# Create the model
model = SVC(kernel='rbf', C=1.0, gamma='scale')  # you can try different kernels like 'linear', 'poly', etc.

# Train the model
model.fit(x_train, y_train)

# Predict on test data
y_pred = model.predict(x_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy*100)

Accuracy: 80.26699401565138